export type AttackAudioType = 'attack1' | 'attack2' | 'attack3';

export const BundleConfig = {
    Names: {
        Baoxiang: 'baoxiang',
        Map: 'map',
        Monsters: 'monsters',
        Music: 'music',
        Resources: 'resources',
        Result: 'result',
        Roles: 'roles',
    },
    AutoLoadBundles: [],
};

export const ResourcePath = {
    Bundle: {
        Baoxiang: 'baoxiang',
        Map: 'map',
        Monsters: 'monsters',
        Music: 'music',
        Resources: 'resources',
        Result: 'result',
        Roles: 'roles',
    },

    Prefab: {
        Box: 'baoxiang/baoxiang/box',
        PowerSuit: 'baoxiang/baoxiang/10004',
        Dao: 'baoxiang/baoxiang/dao',
        Dachui: 'baoxiang/baoxiang/dachui',
        Kuijia: 'baoxiang/baoxiang/kuijia',
        Toukui: 'baoxiang/baoxiang/toukui',

        Role: 'roles/role/role',
        Role1: 'roles/role/role1',
        Role2: 'roles/role/role2',
        Role3: 'roles/role/role3',
        Mount: 'baoxiang/baoxiang/mount',

        Monster1: 'monsters/monster/monster1',
        Monster2: 'monsters/monster/monster2',
        Monster3: 'monsters/monster/monster3',
        Monster4: 'monsters/monster/monster4',
        Monster3Shouji: 'monsters/monster3Spine/1000010shouji',
        Monster3Skill1: 'monsters/monster3Spine/1000010skill1',

        Fail: 'result/fail',
        Victory: 'result/victory',
    },

    Image: {
        Box: 'baoxiang/box',
        MapBg: 'map/bg',

        Role: {
            OrcHero: [
                'roles/兽人主角/100001',
                'roles/兽人主角/100101',
                'roles/兽人主角/100201',
                'roles/兽人主角/100301_l',
                'roles/兽人主角/100301_r',
                'roles/兽人主角/100801_l',
                'roles/兽人主角/100801_r',
                'roles/兽人主角/101101_l',
                'roles/兽人主角/101101_r',
                'roles/兽人主角/face_1',
                'roles/兽人主角/hair_1',
            ],
            ChargeSet: [
                'roles/冲锋套/10009',
                'roles/冲锋套/10109',
                'roles/冲锋套/10209',
                'roles/冲锋套/10309_l',
                'roles/冲锋套/10309_r',
                'roles/冲锋套/10809_l',
                'roles/冲锋套/10809_r',
                'roles/冲锋套/11109_l',
                'roles/冲锋套/11109_r',
            ],
            PowerSet: [
                'roles/力量套/10004',
                'roles/力量套/10104',
                'roles/力量套/10204',
                'roles/力量套/10304_l',
                'roles/力量套/10304_r',
                'roles/力量套/10804_l',
                'roles/力量套/10804_r',
                'roles/力量套/11104_l',
                'roles/力量套/11104_r',
                'roles/力量套/face_1',
                'roles/力量套/hair_1',
            ],
        },

        Monster: {
            UpgradeFrames: [
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_00',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_01',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_02',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_03',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_04',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_05',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_06',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_07',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_08',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_09',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_10',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_11',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_12',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_13',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_14',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_15',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_16',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_17',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_18',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_19',
                'monsters/ui_hero_up_1/ui_hero_up_1-idle_20',
            ],
            SpineTextures: [
                'monsters/地狱火/1070030',
                'monsters/燃刃信徒/1000020',
                // 'monsters/燃刃术士/1000010',
                // 'monsters/燃刃术士/1000010shouji',
                // 'monsters/燃刃术士/1000010skill1',
                'monsters/黑手铁卫士/1000530',
            ],
        },
    },

    Spine: {
        Hit: {
            Attack2: 'roles/effect/hit/100001_hit_2',
            Attack4: 'roles/effect/hit/100001_hit_4',
            ChargeAttack4: 'roles/effect/hit/10009_hit_4',
        },
        Role: {
            OrcHero: [
                'roles/兽人主角/100001',
                'roles/兽人主角/100101',
                'roles/兽人主角/100201',
                'roles/兽人主角/100301_l',
                'roles/兽人主角/100301_r',
                'roles/兽人主角/100801_l',
                'roles/兽人主角/100801_r',
                'roles/兽人主角/101101_l',
                'roles/兽人主角/101101_r',
                'roles/兽人主角/face_1',
                'roles/兽人主角/hair_1',
            ],
            ChargeSet: [
                'roles/冲锋套/10009',
                'roles/冲锋套/10109',
                'roles/冲锋套/10209',
                'roles/冲锋套/10309_l',
                'roles/冲锋套/10309_r',
                'roles/冲锋套/10809_l',
                'roles/冲锋套/10809_r',
                'roles/冲锋套/11109_l',
                'roles/冲锋套/11109_r',
            ],
            PowerSet: [
                'roles/力量套/10004',
                'roles/力量套/10104',
                'roles/力量套/10204',
                'roles/力量套/10304_l',
                'roles/力量套/10304_r',
                'roles/力量套/10804_l',
                'roles/力量套/10804_r',
                'roles/力量套/11104_l',
                'roles/力量套/11104_r',
                'roles/力量套/face_1',
                'roles/力量套/hair_1',
            ],
        },
        Monster: [
            'monsters/地狱火/1070030',
            'monsters/燃刃信徒/1000020',
            'monsters/燃刃术士/1000010',
            'monsters/燃刃术士/1000010shouji',
            'monsters/燃刃术士/1000010skill1',
            'monsters/黑手铁卫士/1000530',
        ],
    },

    Animation: {
        MonsterLevelUp: 'monsters/ani/lv',
    },

    Audio: {
        Bgm: 'music/BGM',
        Attack: 'music/attack1',
        Attack2: 'music/attack2',
        Attack3: 'music/attack3',
        Cheer:  'music/huanhu',
        Shout:  'music/shout',
        HeHa:'music/heha',
        bossAttack:'music/bossAttack',
        bossDie:'music/dead',//bossDie
        MonsterDie: 'music/die',
        RoleDie:'music/roleDie',
        ExpCollect: 'music/jingyan',
        LevelUp: 'music/levelUp',
        Fail: 'music/fail',
        Victory: 'music/victroy',
        RoleBehit:'music/RoleBehit',
        Help1: 'music/Help1',
        Help2: 'music/Help2',
        Roar: 'music/Roar',
        smallAttack:'music/smallAttack',
        bigAttack:'music/bigAttack',
    },
};
